### ISSUE TITLE
I can watch an intro video the first time I create an account 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#30]
I can choose to skip the video by clicking the 'Skip' button

- [ ] YouTube/Vimeo embed
- [ ] Skip button
- [ ] If skip button is selected, direct to Search page

**Comment by RamyAlshurafa** [comment]
Hi @theharrisonmoore 
could you provide us with the intro video link?

**Comment by theharrisonmoore** [comment]
Hi,

I haven't made the video yet. This video will guide the viewer through the
basic features of earwig. Therefore, I'll need the site functioning first
in order to make recordings of it. Is it okay to put a placeholder there
until the video is made?

On the subject of videos on the FAQ, and Useful Stuff pages, I would like
videos to be embedded so users don't have to leave the site to watch them.
Is this going to be possible?

<https://signup.earwig.work/>

**Comment by RamyAlshurafa** [comment]
yeah, that's possible
and we will add a placeholder for now and will be changed when the video is ready

**Comment by theharrisonmoore** [comment]
Perfect, thank you!
<https://signup.earwig.work/>
