### ISSUE TITLE
I can edit my personal info (password, and verification photo) by clicking 'Edit info'

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#57]
- [x] Only relevant for verified users
- [x] Edit info button takes user to edit info screen
- [x] User able to select edit password - must then correctly enter existing password and new password (this could be done via SweetAlert2 potentially)
- [x] User able to edit verification photo (the photo would have been deleted when verified so this would just enable them to upload a new verification photo) 
- [x] Update database

**Comment by thejoefriel** [comment]
Hey @theharrisonmoore - with the verification photo, if they choose to edit (i.e. upload a new verification photo) would that then make them unverified again until you approve?
Also, if you are already verified, just so I understand fully, why would the user want to upload a new verification photo?

**Comment by theharrisonmoore** [comment]
Good one.

Well, it would be a rare event, but they would want to upload a new photo
when they up-skill, or when they replace a lost or stolen card. As I say,
this would be rare because once they've got verified they're unlikely to
think about doing it again. Uploading a new photo would not make them
unverified again.

Primarily, I assumed we'd need this functionality in case they send a photo
that is glary or blurred, meaning they'd need to do it again.

<https://signup.earwig.work/>
