### ISSUE TITLE
When giving reviews, add a drop-out text box to questions irrespective of whether users click yes or no. 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#649]
This is to prevent only capturing negative comments

Video explainer of the user story here: https://drive.google.com/open?id=1w3EWpE70imzdRejPg_l88MbV_qHw8iW-

So to confirm @theharrisonmoore whenever a user answers a yes no question, there will be a text box appear for them to add comments?

Would this be for any other types of questions or purely yes no?

**Comment by theharrisonmoore** [comment]
@thejoefriel this issue is crucial and we must get it right. At the moment, certain questions present a box when the user clicks no (not all questions do this). The change we need to make is only to these existing questions (not any others). So, to be clear, keep the questions, keep the dropdown box, just make the dropdown box appear when the user clicks Yes as well as No.

If I haven't been clear enough, please call me any time and I'll explain more.
