### ISSUE TITLE
When Admin is replying on behalf of entities, lengthy reviews stretch the bounding box too much and the text falls off screen

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#694]
@thejoefriel When Admin is replying on behalf of entities, lengthy reviews stretch the bounding box too much and the text falls off-screen.

iPhone 8, Safari
![IMG_3B81C0E81C4A-1](https://user-images.githubusercontent.com/45825100/65061259-750f9c80-d971-11e9-8765-14cc0b90e70f.jpeg)

MacBook Pro 13, Chrome
<img width="1440" alt="Screenshot 2019-09-17 at 17 37 41" src="https://user-images.githubusercontent.com/45825100/65061460-e2bbc880-d971-11e9-9440-0996eb89e306.png">

**Comment by amusameh** [comment]
Hi @theharrisonmoore 

I think this is because your wrote the whole thing as one word. if you write a normal paragraph it seems to be working fine. 

On the desktop I don't know how it should exactly look like.

**Comment by theharrisonmoore** [comment]
Hi Abdal,

I copied and pasted a body of text into the box, but not as one word.

It's important that we're able to copy and paste bodies of text into the
box because this is exactly what I'll be doing on behalf of companies who
want to reply to workers' comments. Companies will send me their replies by
email and I will then copy and paste their replies into the earwig platform.

-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore pasting lots of content in is absolutely fine, but if you look at your screengrabs you can see that they are including words that have well over 50 characters in them as Abdalsamad mentioned. 

For example, here's where I've pasted in lots of lorem ipsum
![image](https://user-images.githubusercontent.com/19708921/65534289-07c2b500-def7-11e9-9e49-4077b90a1a28.png)

and on mobile:
![image](https://user-images.githubusercontent.com/19708921/65534397-3b9dda80-def7-11e9-95eb-5c4203fe3294.png)

As you can see from the above, it wraps it round accordingly, regardless of the amount of text in there. This also includes very long words that are actual words. 

The problem is if someone puts in an unrealistically long word, so for example like below I've shown you a reply with normal words and one which is just one really long word:
![image](https://user-images.githubusercontent.com/19708921/65535318-114d1c80-def9-11e9-95b3-3a0752158eb7.png)


So I don't think this is a bug as we've covered the user story to cater for realist user behaviour. What do you think?

**Comment by theharrisonmoore** [comment]
@Joe Friel <joe@yallacooperative.com> I see what you mean. That makes
sense. It's highly unlikely users will type one long word. I'm happy for
this issue to be closed.
-

Best,
Harrison Moore

**Comment by thejoefriel** [comment]
Thanks @theharrisonmoore :)
