### ISSUE TITLE
Main contractors list is very slow to load

### ISSUE THREAD

**Issue by theharrisonmoore** [yalla-coop/earwig#936]
@thejoefriel @RamyAlshurafa When giving a worksite review, the main contractors list (all companies) loads very slowly when users click it. I think this is because there are a lot of companies in the list. But it's a problem because workers don't wait long enough for the list to load, and they inevitably click the list multiple times, which only makes things worse. Could we look at fixing this?

**Comment by RamyAlshurafa** [comment]
Hey @theharrisonmoore 
I've been trying to solve this issue for 2 days, but couldn't fix it,
the problem is with the large number of the companies that need to be displayed in the list, so the glitch is clear and obvious on old mobile devices,  so I think we need to let the users search for the company and render the companies that match the search word, and allow them to add new if they want
here an example https://z6t12.csb.app/
what do you think?

**Comment by theharrisonmoore** [comment]
@ramy@yallacooperative.com <ramy@yallacooperative.com> go for it, I think
this is fine for now. We can look at improving it in time.

Best,
Harrison Moore
Sparky & founder
*earwig <http://earwigwork.com>*

ᐧ
